//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public string A_id { get; set; }
        public string Area_name { get; set; }
        public string Alocation { get; set; }
    }
}
