//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public string S_id { get; set; }
        public string Area_id { get; set; }
        public Nullable<System.DateTime> SaddDate { get; set; }
        public Nullable<System.DateTime> SapproveDate { get; set; }
        public string User_id { get; set; }
        public string Disaster_id { get; set; }
        public Nullable<bool> Sstatus { get; set; }
        public string SuserLocation { get; set; }
    }
}
