//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlert
    {
        public string Al_id { get; set; }
        public string Area_id { get; set; }
        public string Disaster_id { get; set; }
        public string ALmessage { get; set; }
        public Nullable<System.DateTime> ALdate { get; set; }
        public string ALriskLevel { get; set; }
        public string ALsafeLocation { get; set; }
    }
}
