//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string U_id { get; set; }
        public string Uname { get; set; }
        public string Uemail { get; set; }
        public string Upassword { get; set; }
    }
}
